module.exports = [
  {
    username: "ernest",
    password: "ernest",
    name: "Ernest",
    email: "ernest@outlook.sg",
    contact: "123456",
    address: "Sin Ming",
    unit: "11-11",
    zipcode: "556677",
  },
  {
    username: "jengmun",
    password: "jengmun",
    name: "Jeng Mun",
    email: "jengmun@yahoo.com",
    contact: "123456",
    address: "Jurong",
    unit: "10-01",
    zipcode: "901132",
  },
  {
    username: "clement",
    password: "clement",
    name: "Clement",
    email: "clement@gmail.com",
    contact: "123456",
    address: "Clementi",
    unit: "11-32",
    zipcode: "123456",
  },
  {
    username: "alex",
    password: "alex",
    name: "Alex",
    email: "alex@outlook.sg",
    contact: "123456",
    address: "Singapore",
    unit: "11-11",
    zipcode: "556677",
  },
  {
    username: "weijie",
    password: "weijie",
    name: "Wei Jie",
    email: "weijie@gmail.com",
    contact: "123456",
    address: "Singapore",
    unit: "11-11",
    zipcode: "556677",
  },
];
